const doctors = [
    {
      id: 1,
      name: "Dr. Aisha Khan",
      medicalName: "Psychiatrist",
      timings: "10:00 AM - 5:00 PM",
      address: "Greenway Clinic, Sector 12, New Delhi",
      experience: "12 years",
      achievements: "Awarded Best Psychiatrist in 2020",
      background: "MD in Psychiatry from AIIMS, New Delhi",
      ratings: 4.8,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1500",
      availability: "Available",
      contact: "+91-9876543210",
      specialization: "Child and Adolescent Mental Health",
      description:
        "Dr. Aisha Khan is a leading expert in child and adolescent mental health. She has over a decade of experience addressing complex cases of depression, anxiety, and PTSD in children and teenagers. Her empathetic approach and tailored treatment plans ensure effective and compassionate care. Patients consistently praise her for her dedication and ability to create a safe, nurturing environment."
    },
    {
      id: 2,
      name: "Dr. Rahul Sharma",
      medicalName: "Clinical Psychologist",
      timings: "11:00 AM - 6:00 PM",
      address: "Harmony Center, MG Road, Mumbai",
      experience: "8 years",
      achievements: "Certified Cognitive Behavioral Therapist",
      background: "PhD in Clinical Psychology from Mumbai University",
      ratings: 4.7,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1200",
      availability: "Available",
      contact: "+91-9876543211",
      specialization: "Cognitive Behavioral Therapy (CBT)",
      description:
        "Dr. Rahul Sharma specializes in Cognitive Behavioral Therapy and mindfulness practices. His sessions focus on helping clients identify and overcome negative thought patterns. With an evidence-based approach, he works closely with patients to tackle challenges like OCD, phobias, and generalized anxiety disorders. Dr. Sharma is known for his calm demeanor and patient-centric therapy sessions."
    },
    {
      id: 3,
      name: "Dr. Meera Banerjee",
      medicalName: "Psychotherapist",
      timings: "9:00 AM - 4:00 PM",
      address: "Mindspace Clinic, Salt Lake City, Kolkata",
      experience: "15 years",
      achievements: "Guest Speaker at International Mental Health Summits",
      background: "Masters in Psychotherapy from Jadavpur University",
      ratings: 4.9,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹2000",
      availability: "Unavailable",
      contact: "+91-9876543212",
      specialization: "Family and Relationship Counseling",
      description:
        "Dr. Meera Banerjee has extensive experience in family and relationship counseling. She provides a safe space for couples and families to navigate challenges and build stronger bonds. Her approach integrates psychodynamic and solution-focused therapies, ensuring practical and long-lasting results. Patients appreciate her warmth and her ability to resolve even the most sensitive issues with care."
    },
    {
      id: 4,
      name: "Dr. Sanjay Patel",
      medicalName: "Psychiatrist",
      timings: "12:00 PM - 8:00 PM",
      address: "Healing Minds Center, Andheri West, Mumbai",
      experience: "10 years",
      achievements: "Authored a Book on Schizophrenia Treatment",
      background: "MD in Psychiatry from KEM Hospital, Mumbai",
      ratings: 4.6,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1800",
      availability: "Available",
      contact: "+91-9876543213",
      specialization: "Schizophrenia and Bipolar Disorder",
      description:
        "Dr. Sanjay Patel is a trusted expert in managing severe mental health conditions like schizophrenia and bipolar disorder. He combines medication management with therapy for comprehensive care. Known for his patient-first attitude, he ensures every individual receives personalized treatment. His commitment to educating patients about their conditions is widely recognized and valued."
    },
    {
      id: 5,
      name: "Dr. Priya Kapoor",
      medicalName: "Psychologist",
      timings: "9:00 AM - 3:00 PM",
      address: "Hope Center, Gachibowli, Hyderabad",
      experience: "7 years",
      achievements: "Certified in Positive Psychology",
      background: "MPhil in Psychology from Osmania University",
      ratings: 4.8,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1000",
      availability: "Available",
      contact: "+91-9876543214",
      specialization: "Stress Management and Emotional Wellness",
      description:
        "Dr. Priya Kapoor focuses on promoting emotional wellness and stress management. She uses techniques from positive psychology and mindfulness to help clients regain balance in their lives. Her empathetic and non-judgmental approach makes her highly sought after, particularly among young professionals dealing with burnout. Patients describe her sessions as transformative and uplifting."
    },
    {
      id: 6,
      name: "Dr. Vikram Desai",
      medicalName: "Child Psychologist",
      timings: "10:00 AM - 5:00 PM",
      address: "Little Steps Clinic, Indiranagar, Bangalore",
      experience: "9 years",
      achievements: "Featured in Parenting Magazines",
      background: "MSc in Child Psychology from NIMHANS, Bangalore",
      ratings: 4.7,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1400",
      availability: "Unavailable",
      contact: "+91-9876543215",
      specialization: "Behavioral Therapy for Children",
      description:
        "Dr. Vikram Desai is dedicated to helping children and adolescents overcome behavioral challenges. His sessions are designed to engage young minds and help them navigate developmental and emotional issues. Parents trust his expertise in building effective strategies for ADHD, autism, and learning disabilities. Dr. Desai is known for his creative and interactive therapeutic methods."
    },
    {
      id: 7,
      name: "Dr. Riya Malhotra",
      medicalName: "Psychiatrist",
      timings: "11:00 AM - 6:00 PM",
      address: "Serenity Clinic, Banjara Hills, Hyderabad",
      experience: "11 years",
      achievements: "Best Mental Health Advocate Award 2021",
      background: "MD in Psychiatry from NIMHANS, Bangalore",
      ratings: 4.9,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1800",
      availability: "Available",
      contact: "+91-9876543216",
      specialization: "Post-Traumatic Stress Disorder (PTSD)",
      description:
        "Dr. Riya Malhotra has a strong reputation for her work with PTSD patients. Her therapy sessions aim to help individuals rebuild their lives and regain confidence after traumatic experiences. Using evidence-based treatments, she focuses on empowering her patients to manage their mental health independently. Dr. Malhotra’s compassionate care has brought hope to many struggling individuals."
    },
    {
      id: 8,
      name: "Dr. Naveen Gupta",
      medicalName: "Neuropsychiatrist",
      timings: "10:00 AM - 4:00 PM",
      address: "Brain and Mind Wellness Center, MG Road, Pune",
      experience: "15 years",
      achievements: "Research Fellow at Global Neuroscience Institute",
      background: "MD in Psychiatry and Neurology from PGIMER, Chandigarh",
      ratings: 4.7,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹2200",
      availability: "Unavailable",
      contact: "+91-9876543217",
      specialization: "Neuropsychiatric Disorders",
      description:
        "Dr. Naveen Gupta is a renowned neuropsychiatrist with expertise in conditions like dementia, Alzheimer's, and Parkinson's disease. He works at the intersection of psychiatry and neurology to provide comprehensive care. His holistic approach ensures that both the mental and physical aspects of these disorders are addressed. Patients and families appreciate his clear communication and dedication."
    },
    {
      id: 9,
      name: "Dr. Arpita Sen",
      medicalName: "Clinical Psychologist",
      timings: "12:00 PM - 7:00 PM",
      address: "Peaceful Minds Clinic, Park Street, Kolkata",
      experience: "9 years",
      achievements: "Certified Trauma and EMDR Specialist",
      background: "PhD in Clinical Psychology from University of Calcutta",
      ratings: 4.8,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1600",
      availability: "Available",
      contact: "+91-9876543218",
      specialization: "Trauma Therapy",
      description:
        "Dr. Arpita Sen specializes in trauma therapy, including Eye Movement Desensitization and Reprocessing (EMDR). She has helped numerous individuals recover from the lasting effects of trauma, enabling them to lead fulfilling lives. Her therapeutic methods are both innovative and effective, and her empathetic nature ensures that patients feel safe throughout their healing journey."
    },
    {
      id: 10,
      name: "Dr. Kunal Jain",
      medicalName: "Psychiatrist",
      timings: "9:00 AM - 2:00 PM",
      address: "Mind Matters Clinic, Connaught Place, New Delhi",
      experience: "10 years",
      achievements: "Guest Lecturer at National Psychiatry Conferences",
      background: "MD in Psychiatry from Maulana Azad Medical College",
      ratings: 4.6,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1500",
      availability: "Available",
      contact: "+91-9876543219",
      specialization: "Addiction Psychiatry",
      description:
        "Dr. Kunal Jain is an experienced psychiatrist specializing in addiction recovery. He has developed a comprehensive treatment program combining medication, counseling, and lifestyle modifications. Dr. Jain’s empathetic and non-judgmental approach has made him a trusted figure among patients and their families."
    },
    {
      id: 11,
      name: "Dr. Sonali Mehta",
      medicalName: "Psychologist",
      timings: "10:00 AM - 5:00 PM",
      address: "Harmony Minds Clinic, Rajajinagar, Bangalore",
      experience: "8 years",
      achievements: "Certified in Mindfulness-Based Therapy",
      background: "Masters in Clinical Psychology from Bangalore University",
      ratings: 4.7,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1200",
      availability: "Available",
      contact: "+91-9876543220",
      specialization: "Mindfulness-Based Cognitive Therapy",
      description:
        "Dr. Sonali Mehta employs mindfulness-based techniques to help individuals struggling with anxiety, depression, and stress. Her holistic approach blends traditional therapy methods with mindfulness practices for long-lasting mental health improvements."
    },
    {
      id: 12,
      name: "Dr. Rohit Kulkarni",
      medicalName: "Psychiatrist",
      timings: "11:00 AM - 7:00 PM",
      address: "New Leaf Psychiatry Center, Koregaon Park, Pune",
      experience: "12 years",
      achievements: "Published Research on Depression Treatments",
      background: "MD in Psychiatry from BJ Medical College, Pune",
      ratings: 4.8,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1800",
      availability: "Available",
      contact: "+91-9876543221",
      specialization: "Mood Disorders",
      description:
        "Dr. Rohit Kulkarni has extensive experience in treating mood disorders such as depression and bipolar disorder. His patient-centric approach ensures every individual feels heard and supported. With cutting-edge treatments and compassionate care, Dr. Kulkarni helps patients regain control over their lives."
    },
    {
      id: 13,
      name: "Dr. Shalini Reddy",
      medicalName: "Counseling Psychologist",
      timings: "9:00 AM - 4:00 PM",
      address: "Care Counsel Clinic, Jubilee Hills, Hyderabad",
      experience: "6 years",
      achievements: "Certified in Dialectical Behavioral Therapy",
      background: "MSc in Counseling Psychology from University of Hyderabad",
      ratings: 4.6,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1000",
      availability: "Available",
      contact: "+91-9876543222",
      specialization: "Dialectical Behavioral Therapy (DBT)",
      description:
        "Dr. Shalini Reddy is skilled in Dialectical Behavioral Therapy, helping clients manage emotional regulation and interpersonal relationships. She is particularly adept at working with clients struggling with borderline personality disorder."
    },
    {
      id: 14,
      name: "Dr. Abhishek Rana",
      medicalName: "Neuropsychologist",
      timings: "10:00 AM - 3:00 PM",
      address: "Brain Balance Clinic, Alwarpet, Chennai",
      experience: "13 years",
      achievements: "Awarded Neuropsychology Innovator 2019",
      background: "PhD in Neuropsychology from Madras University",
      ratings: 4.8,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹2200",
      availability: "Available",
      contact: "+91-9876543223",
      specialization: "Cognitive Rehabilitation",
      description:
        "Dr. Abhishek Rana specializes in cognitive rehabilitation, assisting patients with memory loss, brain injuries, and neurological conditions. He combines innovative methods with patient-focused care to achieve significant improvements."
    },
    {
      id: 15,
      name: "Dr. Leena Deshpande",
      medicalName: "Psychologist",
      timings: "12:00 PM - 8:00 PM",
      address: "Mindful Healing, Navi Mumbai",
      experience: "9 years",
      achievements: "Best Therapist Award 2022",
      background: "Masters in Psychology from University of Mumbai",
      ratings: 4.9,
      image: "/src/assets/doc-default.png",
      consultationFee: "₹1200",
      availability: "Unavailable",
      contact: "+91-9876543224",
      specialization: "Behavioral Therapy",
      description:
        "Dr. Leena Deshpande is an expert in behavioral therapy, focusing on practical solutions to mental health challenges. Her structured approach ensures measurable progress for her clients."
    },
    {
        id: 16,
        name: "Dr. Rajiv Sen",
        medicalName: "Psychiatrist",
        timings: "8:00 AM - 1:00 PM",
        address: "Calm Minds Clinic, Salt Lake, Kolkata",
        experience: "15 years",
        achievements: "Authored 'Modern Psychiatry in India'",
        background: "MD in Psychiatry from AIIMS Delhi",
        ratings: 4.7,
        image: "/src/assets/doc-default.png",
        consultationFee: "₹1600",
        availability: "Available",
        contact: "+91-9876543225",
        specialization: "Schizophrenia and Psychosis",
        description:
          "Dr. Rajiv Sen is a leading expert in managing schizophrenia and psychosis. His holistic approach combines medication with therapy for improved quality of life."
      },
      {
        id: 17,
        name: "Dr. Sneha Kapoor",
        medicalName: "Child Psychologist",
        timings: "9:00 AM - 5:00 PM",
        address: "Happy Minds Center, Jayanagar, Bangalore",
        experience: "7 years",
        achievements: "Specialized in Autism Spectrum Therapy",
        background: "Masters in Child Psychology from NIMHANS",
        ratings: 4.8,
        image: "/src/assets/doc-default.png",
        consultationFee: "₹1400",
        availability: "Available",
        contact: "+91-9876543226",
        specialization: "Autism and ADHD",
        description:
          "Dr. Sneha Kapoor helps children with autism and ADHD develop essential skills. Her compassionate care ensures children feel supported and understood."
      },
      {
        id: 18,
        name: "Dr. Vishal Khanna",
        medicalName: "Psychiatrist",
        timings: "10:00 AM - 3:00 PM",
        address: "Serene Psyche Clinic, Vashi, Navi Mumbai",
        experience: "10 years",
        achievements: "Speaker at International Mental Health Forums",
        background: "MD in Psychiatry from KEM Hospital, Mumbai",
        ratings: 4.7,
        image: "/src/assets/doc-default.png",
        consultationFee: "₹1500",
        availability: "Available",
        contact: "+91-9876543227",
        specialization: "Anxiety Disorders",
        description:
          "Dr. Vishal Khanna specializes in treating anxiety disorders through a mix of cognitive-behavioral therapy and medication."
      },
      {
        id: 19,
        name: "Dr. Pooja Saxena",
        medicalName: "Clinical Psychologist",
        timings: "11:00 AM - 6:00 PM",
        address: "Mind Wellness Center, Sector 18, Noida",
        experience: "8 years",
        achievements: "Awarded 'Best Therapist 2021' by IAMH",
        background: "PhD in Clinical Psychology from Delhi University",
        ratings: 4.9,
        image: "/src/assets/doc-default.png",
        consultationFee: "₹1300",
        availability: "Available",
        contact: "+91-9876543228",
        specialization: "Stress and Trauma Therapy",
        description:
          "Dr. Pooja Saxena focuses on trauma and stress management, offering tailored therapy sessions to help clients regain emotional balance."
      },
      {
        id: 20,
        name: "Dr. Neeraj Gupta",
        medicalName: "Neuropsychiatrist",
        timings: "10:00 AM - 4:00 PM",
        address: "NeuroCare Clinic, Banjara Hills, Hyderabad",
        experience: "14 years",
        achievements: "Research in Neuropsychiatry Innovations",
        background: "MD in Neuropsychiatry from Osmania Medical College",
        ratings: 4.8,
        image: "/src/assets/doc-default.png",
        consultationFee: "₹2000",
        availability: "Available",
        contact: "+91-9876543229",
        specialization: "Neurological Disorders",
        description:
          "Dr. Neeraj Gupta provides expert care for patients with neurological and psychiatric overlaps, ensuring comprehensive recovery."
      },
  ];
  
  export default doctors;
  